version: "3.9"

services:
  spam47:
    build: .
    ports:
      - "8080:80"
    environment:
      - SPAM47_DATAFILE=/data/spam47.gob
      - SPAM47_PORT=80
    volumes:
      - 'data47:/data/'

volumes:
  data47:
    driver: local
